### ISSUE TITLE
Please have copy-paste and drag image to issue helper

### ISSUE THREAD

**Issue by octref** [vuejs/vue-issue-helper#18]
I use Mac's Cmd+Shift+3 to capture image and paste them into GH issues all the time.
I can't do that for vue-issue-helper. What's worse, when I attempted to drag the captured image from desktop to vue-issue-helper, it erased all my written description and back button did not restore anything.

**Comment by octref** [comment]
OK, didn't realize it would link to GitHub new issue (thought it would make the issue for me), so I can still edit and add image. But having to write the issue without adding image isn't a natural workflow...And for me having screenshots / gifs are sometimes essential to describing the issue.

**Comment by yyx990803** [comment]
Yeah, that's a limitation. I don't think GitHub exposes an API for uploading and embedding images in an issue that is not even created. For now, what we can do is probably intercepting the drop event and notify the user about this limitation

**Comment by octref** [comment]
Sounds good. "Drag-n-dropping image clearing all inputted form data" isn't really user-friendly:

![gif](https://cloud.githubusercontent.com/assets/4033249/24845001/917c9ae8-1d7c-11e7-84b7-44e5fbcf6ba3.gif)
