### ISSUE TITLE
Inclue links to starter JSFiddle/ Codesandbox examples for reproductions

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-issue-helper#22]
This is mainly a problem with vue-test-utils.

We ask for a reproduction in JSFiddle, but users struggle to set vue-test-utils up in JSFiddle.

I've created a starter for vue-test-utils—https://jsfiddle.net/eddyerburgh/sghur81m/6/. I'd like to add this link in the issue helper so that users find it easier to create reproductions.

**Comment by yyx990803** [comment]
Sure, feel free to do a PR

**Comment by posva** [comment]
@eddyerburgh `npmcdn` was renamed to `unpkg` so, you should use `unpkg.com` instead (it's the same service, just renamed for legal reasons)
