### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rigor789** [vuejs/vue-issue-helper#24]
I would like to set up this issue helper for NativeScript-Vue, and I was looking for a license in the repository to make sure I'm allowed to do so. 

I could not find any information regarding the license, can you please include one?

Thank you!

**Comment by posva** [comment]
it's probably MIT, but @yyx990803 or @Akryum should say

**Comment by znck** [comment]
It's MIT. I forgot to add before moving it to vuejs organization.

**Comment by rigor789** [comment]
Thank you very much! 🎉 🌮

**Comment by posva** [comment]
lol, sorry! I was quite surprised not to see you on the contributor list while I remember you built a version of this
