### ISSUE TITLE
Issue submission form - changing issue type deletes content

### ISSUE THREAD

**Issue by shawnheide** [vuejs/vue-issue-helper#26]
### Steps to reproduce
Fill out the form on the issue helper (https://new-issue.vuejs.org/?repo=vuejs/vue). Change the type from a Bug Report to a Feature Request. 

### What is expected?
The content in the fields persists. 

### What is actually happening?
The content in the fields is deleted. 

---
This is another small issue, but it really should be more user friendly since you are directing new users here to take the time to submit issues.

**Comment by yyx990803** [comment]
Closed via #28
