### ISSUE TITLE
Submission form always requires a link to code

### ISSUE THREAD

**Issue by Gargo** [vuejs/vue-issue-helper#30]
In general there is too much bureaucratism for one repo, isn't it?

For example I have an issue which is related to `vue-cli` but is not related to any concrete code. In the same time your submission form contains a link field which is required, **not optional** as it should be. What about to fix that?

**Comment by Akryum** [comment]
We have put this issue helper in place to keep the issues manageable. As you may or may not know, we do this work for free and for most of us in our free time. The issue helper is the same for all of our repositories and we ask for a reproduction link so we can quickly try to reproduce the user error. It's marked as a required field so we don't waste time asking for it in each issue.

Unfortunately, it's not adapted to some of the vue cli commands that can't be reproduced in an existing project (thus a reproductible repository). For example, an issue about `vue-cli-service serve` needs to have a reproduction link, but if it's about `vue create` it's not necessary.

We are already in the process of overhauling this for vue-cli which is quite different than every other repository on the Issue Helper, but in the meantime you can put a random link like many other users did already without having to post a disrespectful issue. We are okay with you putting a random link and we have enough brain to tell the difference between the two types of vue-cli issues I mentioned above without closing it mindlessly.
