### ISSUE TITLE
The provided link in the Vue CLI repo issue placeholder text is not working.

### ISSUE THREAD

**Issue by ErikBrown** [vuejs/vue-issue-helper#34]
> IMPORTANT: Please use the following link to create a new issue:
> 
> https://new-issue.vuejs.org/?repo=vuejs/vue-cli
> 
> If your issue was not created using the app above, it will be closed immediately.
> 
> 中文用户请注意：
> 请使用上面的链接来创建新的 issue。如果不是用上述工具创建的 issue 会被自动关闭。

The provided link throws the error `TypeError: "exports" is read-only`

Perhaps it's using the latest Vue Loader and doesn't allow importing `module.exports` anymore.

**Comment by yyx990803** [comment]
Should be back up now.
