### ISSUE TITLE
[Bug] English version using Chinese hint

### ISSUE THREAD

**Issue by Ovilia** [vuejs/vue-issue-helper#38]
The English version of the issue helper uses Chinese hints.

<img width="231" alt="2019-02-15 5 42 17" src="https://user-images.githubusercontent.com/779050/52848320-64801500-3149-11e9-8bab-bd64b4f42a77.png">

Could someone help to fix this, or tell me where to look for so that I could make a PR?

**Comment by Justineo** [comment]
It's the browser's native validation tooltip and it depends on browser locale settings so I think in most cases it won't cause confusion. Though we can fix it with `setCustomValidity` API to enforce consistency, it still requires upstream changes in [vuejs/ui](/vuejs/ui).
