### ISSUE TITLE
codesandbox url is not working in firefox

### ISSUE THREAD

**Issue by derMart** [vuejs/vue-issue-helper#49]
The preview pane in https://codesandbox.io/s/vue
renders nothing and is white in Firefox 73.0.1 Windows 7 x64
Not sure if this is a problem of codesandbox as a whole, or just the template provided by the url above

**Comment by posva** [comment]
Just checked on safari and it works. The template is also right and will work on that version of Firefox. Maybe you have an extension blocking codesandbox behavior. If not, you should report them the issue

**Comment by derMart** [comment]
but Safari is not Firefox...
I just deactivated all extensions, still the problem persists.
![firefox_tpgSWd1sAK](https://user-images.githubusercontent.com/1069456/76238463-2f50d400-6230-11ea-932e-ca020809f6ab.png)
^^here is a screenshot of the console output. Loads of errors related to babel, vue and browserfs.
Could you please link tot eh codesandbox repo, so that I can report a bug there?

**Comment by derMart** [comment]
And Could you please reopen this issue, it is not yet resolved...

**Comment by posva** [comment]
Tested on that exact environment just in case, and it works. It doesn't come from the vue template, that's for sure
<img width="1792" alt="Screenshot 2020-03-09 at 19 07 54" src="https://user-images.githubusercontent.com/664177/76243877-5069f280-6239-11ea-918e-d9642e82ae25.png">

**Comment by derMart** [comment]
this is related to: https://github.com/codesandbox/codesandbox-client/issues/3666
