### ISSUE TITLE
repo name mismatch `vuejs/core` vs `vuejs/vue-next`

### ISSUE THREAD

**Issue by theoephraim** [vuejs/vue-issue-helper#73]
- go to https://github.com/vuejs/core/issues
- click new issue (brings you to https://github.com/vuejs/core/issues/new/choose)
- links to https://new-issue.vuejs.org/?repo=vuejs/core
- redirects to https://new-issue.vuejs.org/?repo=vuejs/vue because vuejs/core does not exist in options list

Mismatch between repo name (`core`) and repo's list config (`vue-next`) defaults back to original vue repo being selected for the issue.

I realized this when I tried to report an issue yesterday, and realized it was posted on the wrong repo!

---

Need to update this [config file](https://github.com/vuejs/vue-issue-helper/blob/master/src/config/repos.js#L4)

I was about to open a PR, but you'll need to make a decision about what the label should be, and "core" could be a bit confusing. 
- maybe the dropdown could be "core (vue 3)"?
- maybe update the vue 2 label as well to "vue (vue 2)"
- Also will likely want to rename some other related files and config (ex: `vue-next-repro-subtitle-links`)

**Comment by LinusBorg** [comment]
This is fixed now :)
